language: python
python:
  - 3.7
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - python -m rasa_nlu.train -c config.yml --data data/nlu.md --verbose && python -m rasa_nlu.server -c config.yml --path models/nlu --response_log models --verbose
script:
  - python test.py
